package gui;

import bd.BDInsertar;
import bd.BDLeer;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import operadora.Cliente;
import operadora.Contrato;
import operadora.LineaMovil;
import utils.Log;

/**
 *
 * @author a21aarondn
 */
public class AñadirLineaMovil extends javax.swing.JDialog {

    /**
     * Creates new form AñadirLineaMovil
     */
    public AñadirLineaMovil(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAñadirLinea = new javax.swing.JPanel();
        lblDNI = new javax.swing.JLabel();
        txtDNICliente = new javax.swing.JTextField();
        separador1 = new javax.swing.JSeparator();
        cmbContratos = new javax.swing.JComboBox<>();
        lblContrato = new javax.swing.JLabel();
        separador2 = new javax.swing.JSeparator();
        btnAñadir = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblDNI.setText("DNI");

        txtDNICliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDNIClienteKeyPressed(evt);
            }
        });

        lblContrato.setText("Contrato");

        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAñadirLineaLayout = new javax.swing.GroupLayout(panelAñadirLinea);
        panelAñadirLinea.setLayout(panelAñadirLineaLayout);
        panelAñadirLineaLayout.setHorizontalGroup(
            panelAñadirLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAñadirLineaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAñadirLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separador1)
                    .addComponent(cmbContratos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelAñadirLineaLayout.createSequentialGroup()
                        .addGroup(panelAñadirLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAñadirLineaLayout.createSequentialGroup()
                                .addComponent(lblDNI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDNICliente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblContrato))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(separador2)
                    .addGroup(panelAñadirLineaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAñadir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerrar)))
                .addContainerGap())
        );
        panelAñadirLineaLayout.setVerticalGroup(
            panelAñadirLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAñadirLineaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAñadirLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDNI)
                    .addComponent(txtDNICliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbContratos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAñadirLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAñadir)
                    .addComponent(btnCerrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAñadirLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAñadirLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDNIClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIClienteKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                Cliente cliente = BDLeer.leerCliente(txtDNICliente.getText());
                ArrayList<Contrato> contratos;
                contratos = BDLeer.listaContratos(txtDNICliente.getText());
                cmbContratos.removeAllItems();
                for (Contrato contrato : contratos) {
                    cmbContratos.addItem(contrato.getId() + " - " + contrato.getIban());
                }
            } catch (SQLException e) {
                System.err.println("No se pudo realizar la acción");
            }
        }
    }//GEN-LAST:event_txtDNIClienteKeyPressed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        try {
            int idContrato;
            String telefono = JOptionPane.showInputDialog(this, "Introduce el número de teléfono", "Atención", JOptionPane.INFORMATION_MESSAGE);
            Double precio = Double.valueOf(JOptionPane.showInputDialog(this, "Introduce el precio", "Atención", JOptionPane.INFORMATION_MESSAGE));

            idContrato = Integer.valueOf(cmbContratos.getSelectedItem().toString().split(" - ")[0]);
            String[] resultado;
            try {
                resultado = BDInsertar.insertarLineaMovil(new LineaMovil(idContrato, telefono, precio));
                if (resultado[0].equals("1")) {
                    Log.escribirLog(Log.INFO, "Línea móvil para el contrato : " + resultado[1]);
                }
            } catch (SQLException e) {
                Log.escribirLog(Log.ERROR, "No se ha podido insertar el cliente: " + e.getSQLState());
            }
        } catch (Exception e) {
            System.err.println("No se pudo completar la acción");
        }
    }//GEN-LAST:event_btnAñadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirLineaMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirLineaMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirLineaMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirLineaMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AñadirLineaMovil dialog = new AñadirLineaMovil(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JComboBox<String> cmbContratos;
    private javax.swing.JLabel lblContrato;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JPanel panelAñadirLinea;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JTextField txtDNICliente;
    // End of variables declaration//GEN-END:variables
}
