package gui;

import bd.BDLeer;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import utils.XML;

/**
 *
 * @author Aarón Durán
 * @author Alejandro Fonterosa
 * @author Germán Vaquero
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        String[] apariencia = XML.leerConfiguracion();
        /*
            Cambiar el tamaño de la fuente implicaría redimensionar los 
            componentes para que se mostrasen correctamente
         */
        Font fuente = new Font(apariencia[0], Integer.valueOf(apariencia[1]), 12);
        // Los botones tienen como parent un JPanel
        for (Component componente : panelPrincipal.getComponents()) {
            if (componente instanceof JButton) {
                JButton boton = (JButton) componente;
                boton.setFont(fuente);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lblBusqueda = new javax.swing.JLabel();
        btnVerCliente = new javax.swing.JButton();
        btnVerTelefono = new javax.swing.JButton();
        separador = new javax.swing.JSeparator();
        lblAñadir = new javax.swing.JLabel();
        btnAñadirCliente = new javax.swing.JButton();
        btnAñadirContrato = new javax.swing.JButton();
        btnAñadirMovil = new javax.swing.JButton();
        btnBuscarNombre = new javax.swing.JButton();
        menuPrincipal = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        mVerRegistro = new javax.swing.JMenuItem();
        mConfiguracion = new javax.swing.JMenuItem();
        mSeparadorArchivo = new javax.swing.JPopupMenu.Separator();
        mSalir = new javax.swing.JMenuItem();
        mClientes = new javax.swing.JMenu();
        mListarClientes = new javax.swing.JMenuItem();
        mAyuda = new javax.swing.JMenu();
        mAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Operadora TeisMobile");
        setResizable(false);

        panelPrincipal.setMinimumSize(new java.awt.Dimension(50, 100));

        lblBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBusqueda.setText("Búsqueda");

        btnVerCliente.setText("DNI");
        btnVerCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerClienteActionPerformed(evt);
            }
        });

        btnVerTelefono.setText("Teléfono");
        btnVerTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTelefonoActionPerformed(evt);
            }
        });

        separador.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblAñadir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAñadir.setText("Añadir");

        btnAñadirCliente.setMnemonic('S');
        btnAñadirCliente.setText("Cliente");
        btnAñadirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirClienteActionPerformed(evt);
            }
        });

        btnAñadirContrato.setText("Contrato");
        btnAñadirContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirContratoActionPerformed(evt);
            }
        });

        btnAñadirMovil.setText("Línea móvil");
        btnAñadirMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirMovilActionPerformed(evt);
            }
        });

        btnBuscarNombre.setText("Nombre/Apell.");
        btnBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblBusqueda)))
                .addGap(39, 39, 39)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAñadirContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAñadirCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAñadirMovil, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAñadir)
                        .addGap(69, 69, 69))))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(lblAñadir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAñadirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAñadirContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAñadirMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(lblBusqueda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnVerCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnVerTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(separador)))
                .addContainerGap())
        );

        mArchivo.setText("Archivo");
        mArchivo.setToolTipText("");

        mVerRegistro.setText("Ver registro...");
        mVerRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mVerRegistroActionPerformed(evt);
            }
        });
        mArchivo.add(mVerRegistro);

        mConfiguracion.setText("Configuración");
        mConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConfiguracionActionPerformed(evt);
            }
        });
        mArchivo.add(mConfiguracion);
        mArchivo.add(mSeparadorArchivo);

        mSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mSalir.setText("Salir...");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        mArchivo.add(mSalir);

        menuPrincipal.add(mArchivo);

        mClientes.setText("Clientes");

        mListarClientes.setText("Listar clientes");
        mListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mListarClientesActionPerformed(evt);
            }
        });
        mClientes.add(mListarClientes);

        menuPrincipal.add(mClientes);

        mAyuda.setText("Ayuda");

        mAcercaDe.setText("Acerca de...");
        mAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAcercaDeActionPerformed(evt);
            }
        });
        mAyuda.add(mAcercaDe);

        menuPrincipal.add(mAyuda);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mListarClientesActionPerformed
        try {
            ListarClientes listarClientes = new ListarClientes(this, rootPaneCheckingEnabled);
            listarClientes.setVisible(true);
        } catch (Exception e) {
            System.err.println("Se canceló la acción");
        }
    }//GEN-LAST:event_mListarClientesActionPerformed

    private void btnVerClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerClienteActionPerformed
        try {
            VerCliente verCliente = new VerCliente(this, rootPaneCheckingEnabled, "");
            verCliente.setVisible(true);

        } catch (Exception e) {
            System.err.println("Se canceló la acción");
        }
    }//GEN-LAST:event_btnVerClienteActionPerformed

    private void btnAñadirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirClienteActionPerformed
        try {
            AñadirCliente añadirCliente = new AñadirCliente(this, rootPaneCheckingEnabled);
            añadirCliente.setVisible(true);
        } catch (Exception e) {
            System.err.println("Se canceló la acción");
        }
    }//GEN-LAST:event_btnAñadirClienteActionPerformed

    private void btnAñadirContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirContratoActionPerformed
        try {
            AñadirContrato añadirContrato = new AñadirContrato(this, rootPaneCheckingEnabled, "");
            añadirContrato.setVisible(true);

        } catch (Exception e) {
            System.err.println("Se canceló la acción");
        }
    }//GEN-LAST:event_btnAñadirContratoActionPerformed

    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
        if (JOptionPane.showOptionDialog(this, "¿Seguro que quieres salir?",
                "Salir...",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new Object[]{"Sí", "Non"},
                "Sí") == 0) {
            System.exit(0);
        };
    }//GEN-LAST:event_mSalirActionPerformed

    private void btnBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNombreActionPerformed
        try {
            BuscarClientes buscarCliente = new BuscarClientes(this, rootPaneCheckingEnabled);
            buscarCliente.setVisible(true);
        } catch (Exception e) {
            System.err.println("Se canceló la acción");
        }
    }//GEN-LAST:event_btnBuscarNombreActionPerformed

    private void mAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAcercaDeActionPerformed
        String acercaDe = "<html><p>Proyecto para la 3ª evaluación de Programación en el ciclo superior de DAW - IES de Teis</p>"
                + "<p>Creado por:</p>"
                + "<ul><li>Aarón Durán</li>"
                + "<li>Alejandro Fonterosa</li>"
                + "<li>Germán Vaquero</li></ul></html>";
        JOptionPane.showMessageDialog(this, acercaDe, "Acerca de...", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mAcercaDeActionPerformed

    private void mVerRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mVerRegistroActionPerformed
        try {
            VerLogs verLogs = new VerLogs(this, rootPaneCheckingEnabled);
            verLogs.setVisible(true);
        } catch (Exception e) {
            System.err.println("Se canceló la acción");
        }
    }//GEN-LAST:event_mVerRegistroActionPerformed

    private void mConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConfiguracionActionPerformed
        try {
            Configuracion configuracion = new Configuracion(this, rootPaneCheckingEnabled);
            configuracion.setVisible(true);
        } catch (Exception e) {
            System.err.println("Se canceló la acción");
        }
    }//GEN-LAST:event_mConfiguracionActionPerformed

    private void btnVerTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTelefonoActionPerformed
        String telefono = "";
        String dni = "";
        try {
            telefono = JOptionPane.showInputDialog(this, "Introduce el teléfono", "Atención", JOptionPane.QUESTION_MESSAGE);
            if (!telefono.isEmpty()) {
                dni = BDLeer.buscarPorTelefono(telefono);
                VerCliente verCliente = new VerCliente(this, rootPaneCheckingEnabled, dni);
                verCliente.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Debes introducir un teléfono", "Error", JOptionPane.ERROR);
            }
        } catch (Exception e) {
            System.err.println("Se canceló la acción");
        }
    }//GEN-LAST:event_btnVerTelefonoActionPerformed

    private void btnAñadirMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirMovilActionPerformed
        try {
            AñadirLineaMovil añadirLineaMovil = new AñadirLineaMovil(this, rootPaneCheckingEnabled);
            añadirLineaMovil.setVisible(true);
        } catch (Exception e) {
            System.err.println("Se canceló la acción");
        }
    }//GEN-LAST:event_btnAñadirMovilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // Set System L&F
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException e) {
            // handle exception
        } catch (ClassNotFoundException e) {
            // handle exception
        } catch (InstantiationException e) {
            // handle exception
        } catch (IllegalAccessException e) {
            // handle exception
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirCliente;
    private javax.swing.JButton btnAñadirContrato;
    private javax.swing.JButton btnAñadirMovil;
    private javax.swing.JButton btnBuscarNombre;
    private javax.swing.JButton btnVerCliente;
    private javax.swing.JButton btnVerTelefono;
    private javax.swing.JLabel lblAñadir;
    private javax.swing.JLabel lblBusqueda;
    private javax.swing.JMenuItem mAcercaDe;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenu mAyuda;
    private javax.swing.JMenu mClientes;
    private javax.swing.JMenuItem mConfiguracion;
    private javax.swing.JMenuItem mListarClientes;
    private javax.swing.JMenuItem mSalir;
    private javax.swing.JPopupMenu.Separator mSeparadorArchivo;
    private javax.swing.JMenuItem mVerRegistro;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JSeparator separador;
    // End of variables declaration//GEN-END:variables
}
