package gui;

import bd.BDLeer;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import operadora.Cliente;
import operadora.Contrato;
import utils.Log;

/**
 *
 * @author Aarón Durán
 * @author Alejandro Fonterosa
 * @author Germán Vaquero
 */
public class VerCliente extends javax.swing.JDialog {

    /**
     * Atributo que almacena el DNI del cliente
     */
    private static String dniCliente;

    /**
     * Creates new form VerCliente
     */
    public VerCliente(java.awt.Frame parent, boolean modal, String dni) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        if (dni.isEmpty()) {
            try {
                this.dniCliente = JOptionPane.showInputDialog("Introduce el DNI:");
                if (this.dniCliente.isEmpty()) {
                    System.err.println("No se ha detectado ningún DNI");
                    dispose();
                }
            } catch (NullPointerException e) {
                System.out.println(e.getMessage());
            }
        } else {
            this.dniCliente = dni;
        }
        try {
            Cliente cliente = BDLeer.leerCliente(dniCliente);
            // Asigna el DNI como título de la ventana
            setTitle(cliente.getDni());
            // Carga todos los campos
            establecerCampoTexto(txtNombreCliente, cliente.getNombre());
            establecerCampoTexto(txtApellido1Cliente, cliente.getApellido1());
            establecerCampoTexto(txtApellido2Cliente, cliente.getApellido2());
            establecerCampoTexto(txtDNICliente, cliente.getDni());
            establecerCampoTexto(txtDomicilioCliente, cliente.getDomicilio());
            establecerCampoTexto(txtNacionalidadCliente, cliente.getNacionalidad().toString());
            establecerCampoTexto(txtLocalidadCliente, cliente.getLocalidad());
            establecerCampoTexto(txtProvinciaCliente, cliente.getProvincia().toString());
            Log.escribirLog(Log.INFO, "Acceso a cliente: " + cliente.getDni());
        } catch (SQLException e) {
            Log.escribirLog(Log.ERROR, e.getSQLState());
        } catch (NullPointerException e) {
            Log.escribirLog(Log.ERROR, e.toString());
        }
        DefaultTableModel tabla = (DefaultTableModel) tblContratos.getModel();
        ArrayList<Contrato> listaContratos = new ArrayList<>();
        Contrato contrato;
        try {
            listaContratos = BDLeer.listaContratos(dniCliente);
            tabla.setRowCount(listaContratos.size());

            tblContratos.setModel(tabla);
            for (int i = 0; i < listaContratos.size(); i++) {
                contrato = listaContratos.get(i);
                tblContratos.setValueAt(contrato.getIban(), i, 0);
                tblContratos.setValueAt(contrato.isFijo(), i, 1);
                tblContratos.setValueAt(contrato.getPrecioFijo(), i, 2);
                tblContratos.setValueAt(contrato.isInternet(), i, 3);
                tblContratos.setValueAt(contrato.getPrecioInternet(), i, 4);
                tblContratos.setValueAt(contrato.isMovil(), i, 5);
                tblContratos.setValueAt(contrato.getId(), i, 6);
            }
            // Oculto la última columna
            tblContratos.getColumnModel().getColumn(6).setMinWidth(0);
            tblContratos.getColumnModel().getColumn(6).setMaxWidth(0);
            tblContratos.getColumnModel().getColumn(6).setWidth(0);
            // Establecer ancho de columna IBAN
            tblContratos.getColumnModel().getColumn(0).setPreferredWidth(145);
        } catch (SQLException e) {
            System.out.println(e.getSQLState());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCliente = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        lblApellido1 = new javax.swing.JLabel();
        txtApellido1Cliente = new javax.swing.JTextField();
        lblApellido2 = new javax.swing.JLabel();
        txtApellido2Cliente = new javax.swing.JTextField();
        lblDNI = new javax.swing.JLabel();
        txtDNICliente = new javax.swing.JTextField();
        lblNacionalidad = new javax.swing.JLabel();
        txtNacionalidadCliente = new javax.swing.JTextField();
        lblDomicilio = new javax.swing.JLabel();
        txtDomicilioCliente = new javax.swing.JTextField();
        lblLocalidad = new javax.swing.JLabel();
        txtLocalidadCliente = new javax.swing.JTextField();
        lblProvincia = new javax.swing.JLabel();
        txtProvinciaCliente = new javax.swing.JTextField();
        panelContratos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblContratos = new javax.swing.JTable();
        btnCerrar = new javax.swing.JButton();
        btnAñadirContrato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del cliente"));

        lblNombre.setText("Nombre");

        txtNombreCliente.setEditable(false);
        txtNombreCliente.setFocusable(false);
        txtNombreCliente.setMaximumSize(new java.awt.Dimension(70, 2147483647));
        txtNombreCliente.setMinimumSize(new java.awt.Dimension(70, 22));

        lblApellido1.setText("Apellido 1");

        txtApellido1Cliente.setEditable(false);
        txtApellido1Cliente.setFocusable(false);

        lblApellido2.setText("Apellido 2");

        txtApellido2Cliente.setEditable(false);
        txtApellido2Cliente.setFocusable(false);

        lblDNI.setText("DNI");

        txtDNICliente.setEditable(false);

        lblNacionalidad.setText("Nacionalidad");

        txtNacionalidadCliente.setEditable(false);
        txtNacionalidadCliente.setFocusable(false);

        lblDomicilio.setText("Domicilio");

        txtDomicilioCliente.setEditable(false);
        txtDomicilioCliente.setFocusable(false);

        lblLocalidad.setText("Localidad");

        txtLocalidadCliente.setEditable(false);

        lblProvincia.setText("Provincia");

        txtProvinciaCliente.setEditable(false);

        javax.swing.GroupLayout panelClienteLayout = new javax.swing.GroupLayout(panelCliente);
        panelCliente.setLayout(panelClienteLayout);
        panelClienteLayout.setHorizontalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDomicilioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDomicilio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLocalidadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLocalidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProvincia)
                            .addComponent(txtProvinciaCliente)))
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelClienteLayout.createSequentialGroup()
                                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtApellido1Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNacionalidadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelClienteLayout.createSequentialGroup()
                                    .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNombre)
                                        .addComponent(lblDNI))
                                    .addGap(78, 78, 78)
                                    .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblApellido1)
                                        .addComponent(lblNacionalidad)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelClienteLayout.createSequentialGroup()
                                    .addComponent(txtDNICliente)
                                    .addGap(82, 82, 82))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApellido2)
                            .addComponent(txtApellido2Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelClienteLayout.setVerticalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblApellido1)
                    .addComponent(lblApellido2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido1Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido2Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDNI)
                    .addComponent(lblNacionalidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDNICliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNacionalidadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDomicilio)
                    .addComponent(lblLocalidad)
                    .addComponent(lblProvincia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDomicilioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLocalidadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProvinciaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelContratos.setBorder(javax.swing.BorderFactory.createTitledBorder("Contratos"));

        tblContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IBAN", "Fijo", "Precio", "Internet", "Precio", "Móvil", "id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class, java.lang.Double.class, java.lang.Boolean.class, java.lang.Double.class, java.lang.Boolean.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblContratos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContratosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblContratos);
        if (tblContratos.getColumnModel().getColumnCount() > 0) {
            tblContratos.getColumnModel().getColumn(6).setPreferredWidth(0);
        }

        javax.swing.GroupLayout panelContratosLayout = new javax.swing.GroupLayout(panelContratos);
        panelContratos.setLayout(panelContratosLayout);
        panelContratosLayout.setHorizontalGroup(
            panelContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContratosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelContratosLayout.setVerticalGroup(
            panelContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContratosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnAñadirContrato.setText("Añadir contrato");
        btnAñadirContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirContratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContratos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAñadirContrato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContratos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnAñadirContrato))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // VISTA

    private void establecerCampoTexto(JTextField campo, String texto) {
        campo.setText(texto);
    }

    private void mostrarDialogoError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    // FIN VISTA
    // CONTROLADOR
    private void tblContratosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContratosMouseClicked
        if (evt.getClickCount() == 2) {
            JTable tabla = (JTable) evt.getSource();
            if (tabla.getValueAt(tabla.getSelectedRow(), 5).toString().equals("true")) {
                try {
                    VerLineasMoviles verLineasMoviles = new VerLineasMoviles(null, rootPaneCheckingEnabled, Integer.parseInt(tabla.getValueAt(tabla.getSelectedRow(), 6).toString()));
                    verLineasMoviles.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                    mostrarDialogoError(e.getMessage());
                }
            }

        }
    }//GEN-LAST:event_tblContratosMouseClicked

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAñadirContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirContratoActionPerformed
        try {
            AñadirContrato añadirContrato = new AñadirContrato(null, rootPaneCheckingEnabled, dniCliente);
            añadirContrato.setVisible(true);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnAñadirContratoActionPerformed
    // FIN CONTROLADOR
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VerCliente dialog = new VerCliente(new javax.swing.JFrame(), true, dniCliente);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirContrato;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblApellido2;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblLocalidad;
    private javax.swing.JLabel lblNacionalidad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblProvincia;
    private javax.swing.JPanel panelCliente;
    private javax.swing.JPanel panelContratos;
    private javax.swing.JTable tblContratos;
    private javax.swing.JTextField txtApellido1Cliente;
    private javax.swing.JTextField txtApellido2Cliente;
    private javax.swing.JTextField txtDNICliente;
    private javax.swing.JTextField txtDomicilioCliente;
    private javax.swing.JTextField txtLocalidadCliente;
    private javax.swing.JTextField txtNacionalidadCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtProvinciaCliente;
    // End of variables declaration//GEN-END:variables
}
